### ISSUE TITLE
Can't build app !!!

### ISSUE THREAD

**Issue by viper4595** [LukeCarrier/android-governor#8]
Hi there !
I'm very happy because of your project.
But i can't build it. 
When i run: $ ./gradlew assemble, errors happend like my image.
I also try with Android Studio and get this error Plugin with id 'com.android.application' not found
<a href="https://tinhte.vn/gallery/photos/67784/" title="67784 by viper4595, on Tinhte.vn"><img src="https://tinhte.vn/store/2016/12/xengallery_photos_l_78215_051bc378ac2277abe0fd8c8f83007e63.png" alt="67784" /></a>
Pleasezzz, help me !!!

**Comment by LukeCarrier** [comment]
Hi @viper4595,

I'm afraid I'm not actively maintaining this project as I simply don't need it any more and I'm maintaining enough code in my professional life that I'm not likely to pick it back up.

I'm sorry, but I'm not sure what's wrong with your build without digging in to it. Gradle has probably changed considerably over the last few years. I hope you get it working -- it'd be great to see someone realise the concept.
